const baseUrl = process.env.BOOKING_BASE_URL ?? 'http://localhost:8080';

function cookiePair(setCookie) {
  return setCookie.split(';')[0];
}

function csrfTokenFromCookie(cookie) {
  const match = cookie.match(/(?:^|;\s*)XSRF-TOKEN=([^;]+)/);
  if (!match) {
    throw new Error('CSRF cookie did not contain XSRF-TOKEN');
  }

  return decodeURIComponent(match[1]);
}

async function request(path, { cookie, csrfToken, ...init } = {}) {
  const response = await fetch(`${baseUrl}${path}`, {
    ...init,
    headers: {
      Accept: 'application/json',
      ...(init.body ? { 'Content-Type': 'application/json' } : {}),
      ...(cookie ? { Cookie: cookie } : {}),
      ...(csrfToken ? { 'X-XSRF-TOKEN': csrfToken } : {}),
      ...init.headers,
    },
  });

  let body = null;
  if (response.status !== 204) {
    try {
      body = await response.json();
    } catch {
      body = null;
    }
  }

  return { response, body };
}

async function createSession() {
  const { response } = await request('/api/auth/csrf');

  if (!response.ok) {
    throw new Error(`Could not initialize CSRF token: ${response.status}`);
  }

  const setCookie = response.headers.get('set-cookie');
  if (!setCookie) {
    throw new Error('CSRF endpoint did not return an XSRF-TOKEN cookie');
  }

  const csrfCookie = cookiePair(setCookie);

  return {
    cookie: csrfCookie,
    csrfToken: csrfTokenFromCookie(csrfCookie),
  };
}

async function login(email, password) {
  const session = await createSession();
  const { response, body } = await request('/api/auth/login', {
    method: 'POST',
    cookie: session.cookie,
    csrfToken: session.csrfToken,
    body: JSON.stringify({ email, password }),
  });

  if (!response.ok) {
    throw new Error(`Login failed for ${email}: ${response.status} ${body?.message ?? ''}`.trim());
  }

  const setCookie = response.headers.get('set-cookie');
  if (!setCookie) {
    throw new Error(`Login for ${email} did not return an auth cookie`);
  }

  return {
    cookie: `${session.cookie}; ${cookiePair(setCookie)}`,
    csrfToken: session.csrfToken,
  };
}

async function createDemoEvent(adminSession) {
  const title = `Concurrency Demo ${new Date().toISOString()}`;
  const { response, body } = await request('/api/events', {
    method: 'POST',
    cookie: adminSession.cookie,
    csrfToken: adminSession.csrfToken,
    body: JSON.stringify({
      title,
      description: 'Generated by the concurrency demo script.',
      dateTime: new Date(Date.now() + 86_400_000).toISOString(),
      venue: 'Concurrency Lab',
      seatCapacity: 1,
    }),
  });

  if (!response.ok) {
    throw new Error(`Could not create demo event: ${response.status} ${body?.message ?? ''}`.trim());
  }

  return body;
}

async function getFirstSeat(userSession, eventId) {
  const { response, body } = await request(`/api/events/${eventId}/seats`, { cookie: userSession.cookie });

  if (!response.ok) {
    throw new Error(`Could not load seats: ${response.status} ${body?.message ?? ''}`.trim());
  }

  const seat = body.find((candidate) => candidate.available);
  if (!seat) {
    throw new Error('Demo event did not contain an available seat');
  }

  return seat;
}

async function bookSeat(session, eventId, seatId) {
  const { response, body } = await request('/api/bookings', {
    method: 'POST',
    cookie: session.cookie,
    csrfToken: session.csrfToken,
    body: JSON.stringify({ eventId, seatId }),
  });

  return {
    status: response.status,
    code: body?.code ?? null,
    seatNumber: body?.seatNumber ?? null,
  };
}

async function main() {
  console.log(`Running concurrency demo against ${baseUrl}`);

  const [adminSession, aliceSession, bobSession] = await Promise.all([
    login('admin@example.com', 'Admin123!'),
    login('alice@example.com', 'Password123!'),
    login('bob@example.com', 'Password123!'),
  ]);

  const event = await createDemoEvent(adminSession);
  const seat = await getFirstSeat(aliceSession, event.id);

  const [aliceResult, bobResult] = await Promise.all([
    bookSeat(aliceSession, event.id, seat.seatId),
    bookSeat(bobSession, event.id, seat.seatId),
  ]);

  const results = [aliceResult, bobResult];
  const createdCount = results.filter((result) => result.status === 201).length;
  const conflictCount = results.filter((result) => result.status === 409 && result.code === 'SEAT_ALREADY_BOOKED').length;

  console.log(`Event: ${event.title} (${event.id})`);
  console.log(`Seat: ${seat.seatNumber} (${seat.seatId})`);
  console.log(`Alice: ${aliceResult.status}${aliceResult.code ? ` ${aliceResult.code}` : ''}`);
  console.log(`Bob: ${bobResult.status}${bobResult.code ? ` ${bobResult.code}` : ''}`);

  if (createdCount !== 1 || conflictCount !== 1) {
    throw new Error(`Expected exactly one 201 and one 409 SEAT_ALREADY_BOOKED, got ${JSON.stringify(results)}`);
  }

  console.log('Result: concurrency guard passed. Exactly one booking succeeded.');
}

main().catch((error) => {
  console.error(error.message);
  process.exit(1);
});
