const baseUrl = process.env.BOOKING_BASE_URL ?? 'http://localhost:8080';

function cookiePair(setCookie) {
  return setCookie.split(';')[0];
}

function csrfTokenFromCookie(cookie) {
  const match = cookie.match(/(?:^|;\s*)XSRF-TOKEN=([^;]+)/);
  if (!match) {
    throw new Error('CSRF cookie did not contain XSRF-TOKEN');
  }

  return decodeURIComponent(match[1]);
}

async function request(path, { cookie, csrfToken, ...init } = {}) {
  const response = await fetch(`${baseUrl}${path}`, {
    ...init,
    headers: {
      Accept: 'application/json',
      ...(init.body ? { 'Content-Type': 'application/json' } : {}),
      ...(cookie ? { Cookie: cookie } : {}),
      ...(csrfToken ? { 'X-XSRF-TOKEN': csrfToken } : {}),
      ...init.headers,
    },
  });

  let body = null;
  if (response.status !== 204) {
    try {
      body = await response.json();
    } catch {
      body = null;
    }
  }

  return { response, body };
}

async function createSession() {
  const { response } = await request('/api/auth/csrf');
  if (!response.ok) {
    throw new Error(`CSRF bootstrap failed: ${response.status}`);
  }

  const setCookie = response.headers.get('set-cookie');
  if (!setCookie) {
    throw new Error('CSRF bootstrap did not return a cookie');
  }

  const cookie = cookiePair(setCookie);
  return { cookie, csrfToken: csrfTokenFromCookie(cookie) };
}

async function login(email, password) {
  const session = await createSession();
  const { response, body } = await request('/api/auth/login', {
    method: 'POST',
    cookie: session.cookie,
    csrfToken: session.csrfToken,
    body: JSON.stringify({ email, password }),
  });

  if (!response.ok) {
    throw new Error(`Login failed for ${email}: ${response.status} ${body?.message ?? ''}`.trim());
  }

  const setCookie = response.headers.get('set-cookie');
  if (!setCookie) {
    throw new Error(`Login for ${email} did not return an auth cookie`);
  }

  return {
    cookie: `${session.cookie}; ${cookiePair(setCookie)}`,
    csrfToken: session.csrfToken,
  };
}

async function main() {
  console.log(`Running smoke test against ${baseUrl}`);

  const admin = await login('admin@example.com', 'Admin123!');
  const title = `Smoke Test Event ${new Date().toISOString()}`;

  const createdEvent = await request('/api/events', {
    method: 'POST',
    cookie: admin.cookie,
    csrfToken: admin.csrfToken,
    body: JSON.stringify({
      title,
      description: 'Generated by the smoke test script.',
      dateTime: new Date(Date.now() + 86_400_000).toISOString(),
      venue: 'Smoke Test Hall',
      seatCapacity: 2,
      status: 'PUBLISHED',
    }),
  });

  if (createdEvent.response.status !== 201) {
    throw new Error(`Create event failed: ${createdEvent.response.status} ${createdEvent.body?.message ?? ''}`.trim());
  }

  const alice = await login('alice@example.com', 'Password123!');
  const bob = await login('bob@example.com', 'Password123!');
  const eventId = createdEvent.body.id;

  const updatedEvent = await request(`/api/events/${eventId}`, {
    method: 'PUT',
    cookie: admin.cookie,
    csrfToken: admin.csrfToken,
    body: JSON.stringify({
      title: `${title} Updated`,
      description: 'Updated by the smoke test script.',
      dateTime: new Date(Date.now() + 86_400_000).toISOString(),
      venue: 'Smoke Test Hall Updated',
      status: 'PUBLISHED',
      seatCapacity: 3,
    }),
  });

  if (updatedEvent.response.status !== 200 || updatedEvent.body.seatsTotal !== 3) {
    throw new Error(`Update event/capacity failed: ${updatedEvent.response.status} ${updatedEvent.body?.message ?? ''}`.trim());
  }

  const adminEvents = await request('/api/admin/events', { cookie: admin.cookie });
  if (adminEvents.response.status !== 200 || !adminEvents.body.some((event) => event.id === eventId)) {
    throw new Error('Created event was not visible in the admin dashboard API');
  }

  const eventDetail = await request(`/api/events/${eventId}`, { cookie: alice.cookie });
  if (eventDetail.response.status !== 200 || eventDetail.body.seatsAvailable !== 3) {
    throw new Error(`Event detail check failed: ${eventDetail.response.status}`);
  }

  const seats = await request(`/api/events/${eventId}/seats`, { cookie: alice.cookie });
  if (seats.response.status !== 200 || !Array.isArray(seats.body) || seats.body.length !== 3) {
    throw new Error(`Seat list check failed: ${seats.response.status}`);
  }

  const availableSeats = seats.body.filter((candidate) => candidate.available);
  if (availableSeats.length !== 3) {
    throw new Error('Expected three generated available seats');
  }

  const booking = await request('/api/bookings/batch', {
    method: 'POST',
    cookie: alice.cookie,
    csrfToken: alice.csrfToken,
    body: JSON.stringify({ eventId, seatIds: availableSeats.map((seat) => seat.seatId) }),
  });

  if (booking.response.status !== 201) {
    throw new Error(`Create batch booking failed: ${booking.response.status} ${booking.body?.message ?? ''}`.trim());
  }

  const waitlist = await request(`/api/events/${eventId}/waitlist`, {
    method: 'POST',
    cookie: bob.cookie,
    csrfToken: bob.csrfToken,
  });

  if (waitlist.response.status !== 204) {
    throw new Error(`Join waitlist failed: ${waitlist.response.status} ${waitlist.body?.message ?? ''}`.trim());
  }

  const bookings = await request('/api/users/me/bookings', { cookie: alice.cookie });
  if (bookings.response.status !== 200 || bookings.body.length < 3) {
    throw new Error('Batch booking was not visible in My bookings');
  }

  const unsafeDelete = await request(`/api/events/${eventId}`, {
    method: 'DELETE',
    cookie: admin.cookie,
    csrfToken: admin.csrfToken,
  });
  if (unsafeDelete.response.status !== 409 || unsafeDelete.body?.code !== 'EVENT_HAS_DEPENDENCIES') {
    throw new Error('Expected deleting an event with bookings/waitlist to be blocked');
  }

  const cancelledBooking = bookings.body[0];
  const cancel = await request(`/api/bookings/${cancelledBooking.id}`, {
    method: 'DELETE',
    cookie: alice.cookie,
    csrfToken: alice.csrfToken,
  });

  if (cancel.response.status !== 204) {
    throw new Error(`Cancel booking failed: ${cancel.response.status}`);
  }

  const refreshedSeats = await request(`/api/events/${eventId}/seats`, { cookie: alice.cookie });
  const refreshedSeat = refreshedSeats.body?.find((candidate) => candidate.seatNumber === cancelledBooking.seatNumber);
  if (!refreshedSeat?.available) {
    throw new Error('Cancelled seat did not become available again');
  }

  const adminWaitlist = await request(`/api/admin/events/${eventId}/waitlist`, { cookie: admin.cookie });
  if (adminWaitlist.response.status !== 200 || !adminWaitlist.body.some((entry) => entry.notifiedAt)) {
    throw new Error('Waitlist entry was not marked as notified after cancellation');
  }

  const emailOutbox = await request('/api/admin/email-outbox', { cookie: admin.cookie });
  if (emailOutbox.response.status !== 200 || emailOutbox.body.length === 0) {
    throw new Error('Expected mock email outbox entries');
  }

  console.log(`Created event: ${title} (${eventId})`);
  console.log(`Batch booked seats: ${availableSeats.map((seat) => seat.seatNumber).join(', ')}`);
  console.log('Verified admin dashboard, capacity update, waitlist notification, blocked delete, and mock email outbox.');
  console.log('Result: smoke test passed.');
}

main().catch((error) => {
  console.error(error.message);
  process.exit(1);
});
